[package]
org = "ballerina"
name = "serdes"
version = "0.1.0"

[[platform.java11.dependency]]
path = "../serdes-native/build/libs/serdes-native-0.1.0-SNAPSHOT.jar"
groupId = "io.ballerina.stdlib.serdes"
artifactId = "serdes"
version = "0.1.0-SNAPSHOT"