name: Build

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.ACCESS_TOKEN }}
        run: ./gradlew build
      - name: Archive Error Log
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Ballerina Internal Log
          path: serdes-ballerina/ballerina-internal.log
          if-no-files-found: ignore
      - name: Generate Codecov Report
        uses: codecov/codecov-action@v1
